// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace day4.Models
{
    [Table("catalog")]
    public partial class catalog
    {
        public catalog()
        {
            photos = new HashSet<photo>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(50)]
        public string name { get; set; }
        public int? admin_id { get; set; }

        [ForeignKey("admin_id")]
        [InverseProperty("catalogs")]
        public virtual user admin { get; set; }
        [InverseProperty("cat")]
        public virtual ICollection<photo> photos { get; set; }
    }
}