// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace day4.Models
{
    [Table("user")]
    public partial class user
    {
        public user()
        {
            Inverseadmin = new HashSet<user>();
            catalogs = new HashSet<catalog>();
            photos = new HashSet<photo>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(100)]
        [Required(ErrorMessage = "*")]
        public string name { get; set; }
        [StringLength(100)]
        [Required(ErrorMessage = "*")]
        [MinLength(3, ErrorMessage = "At Least 3 Char")]
        public string username { get; set; }
        [StringLength(350)]
        [Required(ErrorMessage = "*")]
        [EmailAddress(ErrorMessage = "Invalid Email")]
        public string email { get; set; }
        [StringLength(100)]
        [Required(ErrorMessage = "*")]
        public string password { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "*")]
        [Compare("password", ErrorMessage = "Password Not Match")]
        public string confirm_password { get; set; }

        public string picture { get; set; }
        public int? age { get; set; }
        public int? admin_id { get; set; }

        [ForeignKey("admin_id")]
        [InverseProperty("Inverseadmin")]
        public virtual user admin { get; set; }
        [InverseProperty("admin")]
        public virtual ICollection<user> Inverseadmin { get; set; }
        [InverseProperty("admin")]
        public virtual ICollection<catalog> catalogs { get; set; }
        [InverseProperty("author")]
        public virtual ICollection<photo> photos { get; set; }
    }
}